events {}

http {
  server {
    listen 80;
    server_name proyectofinalso2.duckdns.org;

    location / {
      proxy_pass http://nginx_web:80;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /server/ {
      proxy_pass http://python_web:8080;
      rewrite ^/api(/.*)$ $1 break;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
